version: '3'
services:
    database:
        image: mysql:8.0
        container_name: mysql8
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        volumes:
            - ./db:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_DATABASE=AirFlow
            - MYSQL_ROOT_PASSWORD=root
        networks:
            - webnet

    web:
        build: 
            context: ./
            dockerfile: django.Dockerfile
        command: python3 ./manage.py runserver 0.0.0.0:80
        container_name: AirFlow-Server
        depends_on: 
            - database
        links: 
            - database
        volumes: 
            - ./webapp:/code
        ports:
            - "8080:80"
        networks:
            - webnet

    server-socket:
        build: 
            context: ./
            dockerfile: socket.Dockerfile
        command: python3 ./server_socket.py
        container_name: Socket-Server
        depends_on: 
            - database
        links: 
            - database
        volumes: 
            - ./ServerSocket:/code
        ports:
            - "8081:80"
        networks:
            - webnet

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        depends_on:
            - database
        ports:
            - 8000:80
        environment:
            PMA_HOST: database
            MYSQL_ROOT_PASSWORD: root
        networks:
            - webnet

networks:
    webnet:
